export const CHANGE_RECORD_PICKER_VALUE = "CHANGE_RECORD_PICKER_VALUE";
export const CLEAR_RECORD_PICKER_ERROR = "CLEAR_RECORD_PICKER_ERROR";
export const SET_RECORD_PICKER_ERROR = "SET_RECORD_PICKER_ERROR";
export const SET_RECORD_PICKER_CONFIG = "SET_RECORD_PICKER_CONFIG";