export const SET_CONFIG = "SET_CONFIG";

export const CHANGE_LABEL = "CHANGE_LABEL";
export const CHANGE_PLACEHOLDER = "CHANGE_PLACEHOLDER";
export const CHANGE_OBJECT_API_NAME = "CHANGE_OBJECT_API_NAME";

export const ADD_FILTER_CRITERIA = "ADD_FILTER_CRITERIA";
export const REMOVE_FILTER_CRITERIA = "REMOVE_FILTER_CRITERIA";
export const CHANGE_FILTER_CRITERIA_FIELD_PATH =
    "CHANGE_FILTER_CRITERIA_FIELD_PATH";
export const CHANGE_FILTER_CRITERIA_OPERATOR =
    "CHANGE_FILTER_CRITERIA_OPERATOR";
export const CHANGE_FILTER_CRITERIA_VALUE = "CHANGE_FILTER_CRITERIA_VALUE";
export const CHANGE_FILTER_LOGIC = "CHANGE_FILTER_LOGIC";

export const CHANGE_PRIMARY_DISPLAY_FIELD = "CHANGE_PRIMARY_DISPLAY_FIELD";
export const CHANGE_ADDITIONAL_DISPLAY_FIELD =
    "CHANGE_ADDITIONAL_DISPLAY_FIELD";

export const CHANGE_PRIMARY_MATCHING_FIELD = "CHANGE_PRIMARY_MATCHING_FIELD";
export const CHANGE_PRIMARY_MATCHING_FIELD_MODE =
    "CHANGE_PRIMARY_MATCHING_FIELD_MODE";
export const CHANGE_ADDITIONAL_MATCHING_FIELD =
    "CHANGE_ADDITIONAL_MATCHING_FIELD";
